### ISSUE TITLE
Hints enhancement

### ISSUE THREAD

**Issue by himalczyk** [pasiasty/cocoder#3]
Hints showing function as a casual text. It would be nice if it would recognize what is text and what is a function showing a specific icon to separate what we want to use/call :)
![image](https://user-images.githubusercontent.com/49282249/150009738-54941634-d5a0-4ad5-a30d-82337dcf4de1.png)
Example:
![image](https://user-images.githubusercontent.com/49282249/150009814-d2dc6d44-2197-4943-b62d-074711d7ec55.png)

**Comment by pasiasty** [comment]
Well, that's because Monaco editor does only support syntax coloring for most languages at the moment: ![Monaco documentation](https://user-images.githubusercontent.com/13727560/156843262-4f15788f-67eb-493d-816e-5ae81d78a10c.png).

It is technically possible to get proper IntelliSense for other languages as well, but at the moment it requires some extra hops and doesn't seem to be worth the effort for now :)

For future reference I'll add here a post that contains some hints on how to do that. Perhaps some contributor will use that in the future 😉 

https://github.com/microsoft/monaco-editor/issues/421#issuecomment-296102604
